export default {
  // General
  "General.menu": "speisekarte",
  "General.login": "einloggen",
  "General.logout": "ausloggen",
  "General.username": "nutzername",
  "General.password": "passwort",
  "General.time": "zeit",
  "General.place": "ort",
  "General.createdBy": "Erstellt von",
  "General.similarEvents": "Ähnliche Veranstaltungen",
  "General.submit": "einreichen",
  "General.create": "erstellen",
  "General.update": "aktualisieren",
  "General.back": "zurück",
  "General.of": "von",
  "General.rowsPerPage": "Zeilen pro Seite",
  "General.price": "Preis",
  "General.typePrice": "Preis eingeben",
  "General.tags": "Stichworte",
  "General.typeTags": "Tags eingeben",
  "General.coordinates": "Koordinaten",
  "General.typeCoordinates": "Koordinaten eingeben",
  "General.register": "Registrieren",
  "General.gender": "Geschlecht",
  "General.birthDate": "Geburtsdatum",

  // Auth
  "Auth.passwordReset": "Passwort zurücksetzen",
  "Auth.login": "einloggen",
  "Auth.register": "registrieren",
  "Auth.backToLogin": "Zurück zur Anmeldung",
  "Auth.login.403": "Falsche Benutzeranmeldeinformationen",
  "Auth.login.404":
    "Benutzer mit der angegebenen E-Mail-Adresse konnte nicht gefunden werden",
  "Auth.passwordResetSent":
    "E-Mail mit Anweisungen wurde an Ihre E-Mail-Adresse gesendet.",

  // Event
  "Event.create": "Event erstellen",
  "Event.update": "Ereignis aktualisieren",
  "EventList.heading": "Beliebte Veranstaltungen in",
  "Event.details": "Veranstaltungsdetails",
  "Event.uploadImages": "Bilder hochladen",
  "Event.moreEventsIn": "Weitere Veranstaltungen",
  "Event.name": "Veranstaltungsname",
  "Event.typeName": "Geben Sie den Ereignisnamen ein",
  "Event.date": "Veranstaltungsdatum",
  "Event.dateSelect": "Ereignisdatum auswählen",
  "Event.category": "Kategorie",
  "Event.description": "Beschreibung",
  "Event.typeDescription": "Typbeschreibung",

  // Event categories
  "Event.category.music": "Musik",
  "Event.category.art": "Kunst",
  "Event.category.business": "Geschäft",
  "Event.category.parties": "Parteien",
  "Event.category.classes": "Klassen",
  "Event.category.sport": "Sport",
  "Event.category.wellness": "Wellness",
  "Event.category.food": "Essen",
  "Event.category.fun": "Spaß",
  "Event.category.movie": "Film",
  "Event.category.party": "Party",
  "Event.category.family": "Familie",
  "Event.category.outdoor": "Draussen",
  "Event.category.nature": "Natur",
  "Event.category.other": "Andere",

  // User
  "User.profile": "Benutzerprofil",
  "User.register": "Benutzer registrieren",
  "User.update": "Benutzer aktualisieren",
  "User.uploadPhoto": "Foto hochladen",
  "User.address": "Adresse",
  "User.info": "Benutzerinformation",
  "User.userName": "User name",
  "User.typeUserName": "Type user name",
  "User.firstName": "First name",
  "User.typeFirstName": "Type first name",
  "User.lastName": "Last name",
  "User.typeLastName": "Type last name",
  "User.email": "Email",
  "User.typeEmail": "Type email",
  "User.phone": "Phone",
  "User.typePhone": "Type phone",
  "User.password": "Password",
  "User.typePassword": "Type password",
  "User.confirmPassword": "Confirm password",
  "User.typeConfirmPassword": "Type confirm password",

  // Form
  "Form.validations.invalidEmail": "Ungültige e-mail",
  "Form.validations.required": "Dieses Feld wird benötigt",
  "Form.validations.max": "Maximal 255 Zeichen sind zulässig",
  "Form.validations.min": "Es sind mindestens 5 Zeichen erforderlich",
  "Form.validations.string": "Muss ein String sein",
  "Form.validations.passwordMatch": "Passwort muss übereinstimmen",
  "Form.validations.pattern": "Please type phone number in pattern",

  "From.address.street": "Straße",
  "From.address.typeStreet": "Straße eingeben",
  "From.address.zipCode": "Postleitzahl",
  "From.address.typeZipCode": "Geben Sie die Postleitzahl ein",
  "From.address.city": "Stadt",
  "From.address.typeCity": "Geben Sie city ein",
  "From.address.country": "Land",
  "From.address.typeCountry": "Land eingeben",

  // Messages
  "Messages.signUpRequired":
    "Sie müssen angemeldet sein, bevor Sie ein Ereignis erstellen können."
};
