export default {
  // General
  "General.menu": "menu",
  "General.login": "log in",
  "General.logout": "log out",
  "General.username": "user name",
  "General.password": "password",
  "General.time": "time",
  "General.place": "place",
  "General.createdBy": "created by",
  "General.similarEvents": "Similar Events",
  "General.submit": "submit",
  "General.create": "create",
  "General.update": "update",
  "General.back": "back",
  "General.of": "of",
  "General.rowsPerPage": "Rows Per Page",
  "General.price": "Price",
  "General.typePrice": "Type price",
  "General.tags": "Tags",
  "General.typeTags": "Type tags",
  "General.coordinates": "Coordinates",
  "General.typeCoordinates": "Type coordinates",
  "General.register": "Register",
  "General.gender": "Gender",
  "General.birthDate": "Birth date",

  // Auth
  "Auth.passwordReset": "password reset",
  "Auth.login": "login",
  "Auth.register": "register",
  "Auth.backToLogin": "Back to login",
  "Auth.login.403": "Wrong user credentials",
  "Auth.login.404": "Unable to find user with given email address",
  "Auth.passwordResetSent":
    "Email with instructions has been sent to your email address.",

  // Event
  "Event.create": "Create event",
  "Event.update": "Update event",
  "EventList.heading": "Popular Events in",
  "Event.details": "Event details",
  "Event.uploadImages": "Upload images",
  "Event.moreEventsIn": "More events in",
  "Event.name": "Event name",
  "Event.typeName": "Type event name",
  "Event.date": "Event date",
  "Event.dateSelect": "Select event date",
  "Event.category": "Category",
  "Event.description": "Description",
  "Event.typeDescription": "Type description",

  // Event categories
  "Event.category.music": "Music",
  "Event.category.art": "Art",
  "Event.category.business": "Business",
  "Event.category.parties": "Parties",
  "Event.category.classes": "Classes",
  "Event.category.sport": "Sport",
  "Event.category.wellness": "Wellness",
  "Event.category.food": "Food",
  "Event.category.fun": "Fun",
  "Event.category.movie": "Movie",
  "Event.category.party": "Party",
  "Event.category.family": "Family",
  "Event.category.outdoor": "Outdoor",
  "Event.category.nature": "Nature",
  "Event.category.other": "Other",

  // User
  "User.profile": "User profile",
  "User.register": "Register user",
  "User.update": "Update user",
  "User.uploadPhoto": "Upload photo",
  "User.address": "Address",
  "User.info": "User Info",
  "User.userName": "Nutzername",
  "User.typeUserName": "Geben Sie den Benutzernamen ein",
  "User.firstName": "Vorname",
  "User.typeFirstName": "Vorname eingeben",
  "User.lastName": "Nachname",
  "User.typeLastName": "Nachname eingeben",
  "User.email": "Email",
  "User.typeEmail": "E-Mail eingeben",
  "User.phone": "Telefon",
  "User.typePhone": "Geben Sie Telefon ein",
  "User.password": "Passwort",
  "User.typePassword": "Passwort eingeben",
  "User.confirmPassword": "Passwort bestätigen",
  "User.typeConfirmPassword": "Geben Sie Confirm password ein",

  // Form
  "Form.validations.invalidEmail": "Invalid email",
  "Form.validations.required": "This field is required",
  "Form.validations.max": "Maximum of 255 characters are allowed",
  "Form.validations.min": "Minimum of 5 characters are required",
  "Form.validations.string": "Has to be string value",
  "Form.validations.passwordMatch": "Password must match",
  "Form.validations.pattern": "Please type phone number in pattern",

  "From.address.street": "Street",
  "From.address.typeStreet": "Type street",
  "From.address.zipCode": "Zip Code",
  "From.address.typeZipCode": "Type Zip Code",
  "From.address.city": "City",
  "From.address.typeCity": "Type city",
  "From.address.country": "Country",
  "From.address.typeCountry": "Type country",

  // Messages
  "Messages.signUpRequired":
    "You need to be logged in before you can create event"
};
