import { IEvent } from "redux/events/types";

export const mockedEvents = [
  {
    _id: "5e0dc1f3adec140017cadac7",
    name: "Art Battle New York",
    description: "Art Battle New York at Le Poisson Rouge",
    date: 1604916480000,
    imageUrl:
      "https://local-events-react.s3.us-east-2.amazonaws.com/2020-01-02T10%3A12%3A02.739Z-art-battle-ny.jpg",
    price: {
      price: 11,
      currency: "EUR",
      locale: "en",
    },
    address: {
      street: "Radlinskeho 34",
      postalCode: "81710",
      city: "Bratislava",
      countryCode: "SK",
      country: "SM",
    },
    category: ["art", "sport", "foor"],
    similarEvents: [],
    coordinates: [40.7285022, -74.0022365],
    tags: ["Art", "Outdoor", "Paint"],
    owner: {
      address: {
        street: "Radlinskeho 34",
        postalCode: "81710",
        city: "Bratislava",
        countryCode: "SK",
        country: "SM",
      },
      userRole: "admin",
      _id: "5d700df7dd776d0a9d0c0e17",
      firstName: "Martin",
      lastName: "Zahradnik",
      userName: "Matty",
      birthDate: 637754760000,
      phone: "+42190749188",
      image:
        "https://local-events-react.s3.us-east-2.amazonaws.com/2020-02-01T10%3A07%3A17.269Z-IMG_20190601_193137.jpg",
      email: "zahradnik.admin@gmail.com",
    },
  },
  {
    price: {
      price: 0,
      currency: "EUR",
      locale: "en",
    },
    address: {
      street: "Le Poisson Rouge, 158 Bleecker Street",
      postalCode: "10001",
      city: "New York",
      countryCode: "US",
      country: "United States",
    },
    category: ["art"],
    coordinates: [40.7285022, -74.0022365],
    similarEvents: [],
    tags: ["Art"],
    _id: "5e0dc1f3adec140017cada23",
    name: "Art Battle New York",
    description: "Art Battle New York at Le Poisson Rouge",
    date: 1604916480000,
    imageUrl:
      "https://local-events-react.s3.us-east-2.amazonaws.com/2020-01-02T10%3A12%3A02.739Z-art-battle-ny.jpg",
    owner: {
      address: {
        street: "Radlinskeho 34",
        postalCode: "81710",
        city: "Bratislava",
        countryCode: "SK",
        country: "SM",
      },
      userRole: "admin",
      _id: "5d700df7dd776d0a9d0c0e17",
      firstName: "Martin",
      lastName: "Zahradnik",
      userName: "Matty",
      birthDate: 637754760000,
      phone: "+42190749188",
      image:
        "https://local-events-react.s3.us-east-2.amazonaws.com/2020-02-01T10%3A07%3A17.269Z-IMG_20190601_193137.jpg",
      email: "zahradnik.admin@gmail.com",
      gender: "male",
    },
  },
  {
    price: {
      price: 20,
      currency: "EUR",
      locale: "en",
    },
    address: {
      street: "The Empire Rooftop, 44 W 63rd St",
      postalCode: "",
      city: "New York City",
      countryCode: "US",
      country: "United States",
    },
    category: ["business"],
    coordinates: [40.7715082, -73.9849025],
    similarEvents: [],
    tags: ["business", " parties", " sports", " art"],
    _id: "5e09e5aae3ef9da811048803",
    name: "Entrepreneurs and Business Professionals Networking Event",
    description:
      "Join Us on Tuesday, January 7th for our very exclusive International Night at The Empire Rooftop.\n\nNetwork and mingle with Elite International Business Executives while enjoying a Signature Empire Sunset Cocktail. Located on top of the iconic Empire Hotel, The Empire Rooftop boasts views of Lincoln Center and Manhattan's West Side.\n\nOur events are designed to bring together NYC most influential professionals, including real estate developers, brokers / agents, artist, designers, architects, investors, lenders, lawyers, business owners, potential clients, executives and ambitious entrepreneurs of New York.\n\nAt The International Night, we will connect you with a wide Network of people that will contribute to your success. Bring lots of business cards and don't miss this opportunity to promote both yourself and your Business, or simply mingle among the best of New York City. \n\nWHAT TO EXPECT:\n\nNo Cover Charge! No Entrance fee! No Table Fee! (Purchase of 1 Drink Minimum per person)",
    date: 1602758940000,
    imageUrl:
      "https://local-events-react.s3.us-east-2.amazonaws.com/2019-12-30T11%3A55%3A20.564Z-entrepreneurs-and-business.jpg",
    owner: {
      address: {
        street: "Radlinskeho 34",
        postalCode: "81710",
        city: "Bratislava",
        countryCode: "SK",
        country: "SM",
      },
      userRole: "admin",
      _id: "5d700df7dd776d0a9d0c0e17",
      firstName: "Martin",
      lastName: "Zahradnik",
      userName: "Matty",
      birthDate: 637754760000,
      phone: "+42190749188",
      image:
        "https://local-events-react.s3.us-east-2.amazonaws.com/2020-02-01T10%3A07%3A17.269Z-IMG_20190601_193137.jpg",
      email: "zahradnik.admin@gmail.com",
      gender: "male",
    },
  },
  {
    price: {
      price: 12,
      currency: "EUR",
      locale: "en",
    },
    address: {
      street: "Ravensbourne University London, 6 Penrose Way",
      postalCode: "SE100EW",
      city: "London",
      countryCode: "GB",
      country: "United Kingdom",
    },
    category: ["other"],
    coordinates: [51.5016728, 0.0035556],
    similarEvents: [],
    tags: ["Workshop", "Journalism"],
    _id: "5e0f0f688452210017d775b2",
    name: "Mobile Phone Journalism",
    description:
      "On this course, you will learn the following.....\n\nSession One: Framing the mobile phone narrative\n\nYou will be introduced to the concepts of how to structure and tell a mobile phone journalistic captured story. \n\nSession Two: Camera, lights & sound workshop\n\nDuring this practical, hands on, fast paced session; you will be able to explore how simple lighting and sound capture for mobile phones can be used to enhance your narrative. \n\nSession Three: Researching the truth\n\nJournalism's first obligation is to find the truth… learn good storytelling techniques based on this principle as this is paramount to keeping the audience captive. \n\nSession Four:  Distribute your message \n\nLearn how to webcast your pre-recorded material or go live on social media. You will also discover how to publish utilising augmented reality storytelling techniques.\n\nSession Five: Final Content creation\n\nDuring our final session you will have the chance to consolidate their new found skills to create a final piece of work. You will work in small production groups (or by yourself) to pre-produce material ready for publication live or at a later date.",
    date: 1597310640000,
    imageUrl:
      "https://local-events-react.s3.us-east-2.amazonaws.com/2020-01-03T09%3A54%3A47.394Z-mobile-journalism.jpg",
    owner: {
      address: {
        street: "Radlinskeho 34",
        postalCode: "81710",
        city: "Bratislava",
        countryCode: "SK",
        country: "SM",
      },
      userRole: "admin",
      _id: "5d700df7dd776d0a9d0c0e17",
      firstName: "Martin",
      lastName: "Zahradnik",
      userName: "Matty",
      birthDate: 637754760000,
      phone: "+42190749188",
      image:
        "https://local-events-react.s3.us-east-2.amazonaws.com/2020-02-01T10%3A07%3A17.269Z-IMG_20190601_193137.jpg",
      email: "zahradnik.admin@gmail.com",
      gender: "male",
    },
  },

  {
    price: {
      price: 33,
      currency: "EUR",
      locale: "en",
    },
    address: {
      street: "216 West 116th Street",
      postalCode: "10001",
      city: "New York",
      countryCode: "US",
      country: "Australia",
    },
    category: ["parties", "music", "art"],
    coordinates: [40.8034436, -73.9556327],
    similarEvents: [],
    tags: ["Dance", "Africa", "Party", "New York"],
    _id: "5e08cdf8540692979940896f",
    name: "Go Africa Carnival 2020",
    description:
      "Celebrating African, African-American & Caribbean cultures from all parts of the world\n\n This year’s Carnival  bring new artists up to 3 stages throughout both days of the event thus providing something fresh and exciting for all New Yorkers.\n\n The Go Africa Master Chefs will be on 8 grills cooking up African, Caribbean, and American specialties for the duration of the street festival.\n\n The Go Africa Master Chefs will be cooking it up in addition to the other featured food merchants at the street Festival to increase your food choices and eating pleasures.",
    date: 1596287220000,
    imageUrl:
      "https://local-events-react.s3.amazonaws.com/2019-12-30T14%3A11%3A07.964Z-go-africa.jpg",
    owner: {
      address: {
        street: "Radlinskeho 34",
        postalCode: "81710",
        city: "Bratislava",
        countryCode: "SK",
        country: "SM",
      },
      userRole: "admin",
      _id: "5d700df7dd776d0a9d0c0e17",
      firstName: "Martin",
      lastName: "Zahradnik",
      userName: "Matty",
      birthDate: 637754760000,
      phone: "+42190749188",
      image:
        "https://local-events-react.s3.us-east-2.amazonaws.com/2020-02-01T10%3A07%3A17.269Z-IMG_20190601_193137.jpg",
      email: "zahradnik.admin@gmail.com",
      gender: "male",
    },
  },
  {
    price: {
      price: 0,
      currency: "EUR",
      locale: "en",
    },
    address: {
      street: "NEST+m, 111 Columbia Street",
      postalCode: "10001",
      city: "New York",
      countryCode: "US",
      country: "United States",
    },
    category: ["sport"],
    coordinates: [40.7195002, -73.9814332],
    similarEvents: [],
    tags: ["Chess", " NYC", " New York"],
    _id: "5e119dcca3cce50017d24405",
    name: "Chess Team Tryouts",
    description:
      "This club is for students who are interested in deepening their chess knowledge and competition. Taught by Grand Master, Tamaz Gelashvili, Instruction will largely focus on analysis of top games, as well as middle and end game strategies, and will include weekly homework assignments. This competitive team will consist of 15 players based on USCF ratings. Participants who do not have a rating can attend tryouts to receive an equivalency rating. ",
    date: 1595488500000,
    imageUrl:
      "https://local-events-react.s3.us-east-2.amazonaws.com/2020-01-05T08%3A26%3A50.312Z-chees.jpeg",
    owner: {
      address: {
        street: "Radlinskeho 34",
        postalCode: "81710",
        city: "Bratislava",
        countryCode: "SK",
        country: "SM",
      },
      userRole: "admin",
      _id: "5d700df7dd776d0a9d0c0e17",
      firstName: "Martin",
      lastName: "Zahradnik",
      userName: "Matty",
      birthDate: 637754760000,
      phone: "+42190749188",
      image:
        "https://local-events-react.s3.us-east-2.amazonaws.com/2020-02-01T10%3A07%3A17.269Z-IMG_20190601_193137.jpg",
      email: "zahradnik.admin@gmail.com",
      gender: "male",
    },
  },
  {
    price: {
      price: 2500,
      currency: "EUR",
      locale: "en",
    },
    address: {
      street: "Alexander House, 155-157 Merton Rd",
      postalCode: "SW185EQ",
      city: "London",
      countryCode: "GB",
      country: "United Kingdom",
    },
    category: ["other"],
    coordinates: [51.4509112, -0.200482],
    similarEvents: [],
    tags: ["Coding Programing Data Science Workshop"],
    _id: "5e0f10898452210017d775b3",
    name: "Data Science",
    description:
      "Data Science Course Information\n\nDuration: 10 days (60 Hours)\n\n\nWeek day Batches: ( Mon to Fri 10am to 4pm ) 10 Days\n\nWeekends Batches: ( Sat & Sun 10am to 4pm ) 5 weekends\n\n\nTraining Highlights\n\n\nInstructor Led – Face2Face / class room training\n\nMore interaction with student to faculty and student to student.\n\nDetailed presentations. Soft copy of Material to refer any time.\n\nPractical oriented / Job oriented Training. Practice on Software Tools & Real Time project scenarios.\n\nMock interviews / group discussions / interview related questions.\n\nTest Lab is in Cloud Technology – to practice on software tools if needed.\n\nWe discuss about the real time project domains.\n\nThe teaching methods / tools / topics we chosen are based on the current competitive job market.\n\n\nAlso on this course we offer the following\n\n\nHands on Experience\n\nReal Time project work\n\nInterview based Training\n\n\nPre-Requisites\n\n\nPrevious Educational Background in IT or experience in support of networking.",
    date: 1595061840000,
    imageUrl:
      "https://local-events-react.s3.us-east-2.amazonaws.com/2020-02-01T09%3A43%3A43.335Z-data-science.jpg",
    owner: {
      address: {
        street: "Radlinskeho 34",
        postalCode: "81710",
        city: "Bratislava",
        countryCode: "SK",
        country: "SM",
      },
      userRole: "admin",
      _id: "5d700df7dd776d0a9d0c0e17",
      firstName: "Martin",
      lastName: "Zahradnik",
      userName: "Matty",
      birthDate: 637754760000,
      phone: "+42190749188",
      image:
        "https://local-events-react.s3.us-east-2.amazonaws.com/2020-02-01T10%3A07%3A17.269Z-IMG_20190601_193137.jpg",
      email: "zahradnik.admin@gmail.com",
      gender: "male",
    },
  },
  {
    price: {
      price: 0,
      currency: "EUR",
      locale: "en",
    },
    address: {
      street: "Art4Space, 31 Jeffreys Rd, Stockwell",
      postalCode: "SW46QU",
      city: "London",
      countryCode: "GB",
      country: "Australia",
    },
    category: ["wellness", "sport"],
    coordinates: [51, 23],
    similarEvents: [],
    tags: ["Workshops", " Health", "Welness"],
    _id: "5e08ce165406929799408970",
    name: "Reboot Camp 2020",
    description:
      "New year, refresh, renew and replenish your life. Are you ready to let go of people, habits and expectations that no longer serve you?\n\nDo you love your life but find yourself overwhelmed with commitments? Saying yes to too many people in work and your personal life?\n\nPress pause; take time out to reboot your life, check in with what’s working for you and how to change what’s not!\n\nThrough self-reflection space, small groups and some playfulness this day retreat aims to provide you with ideas to re-energize, create connections and apply research from positive psychology to continued professional & personal development. Expect to have fun, reignite your passion and joy for who you are in the world!",
    date: 1594990680000,
    imageUrl:
      "https://local-events-react.s3.us-east-2.amazonaws.com/2019-12-30T10%3A27%3A03.971Z-2019-12-30T10_09_30.170Z-reboot%20%281%29.png",
    owner: {
      address: {
        street: "Radlinskeho 34",
        postalCode: "81710",
        city: "Bratislava",
        countryCode: "SK",
        country: "SM",
      },
      userRole: "admin",
      _id: "5d700df7dd776d0a9d0c0e17",
      firstName: "Martin",
      lastName: "Zahradnik",
      userName: "Matty",
      birthDate: 637754760000,
      phone: "+42190749188",
      image:
        "https://local-events-react.s3.us-east-2.amazonaws.com/2020-02-01T10%3A07%3A17.269Z-IMG_20190601_193137.jpg",
      email: "zahradnik.admin@gmail.com",
      gender: "male",
    },
  },
  {
    price: {
      price: 0,
      currency: "EUR",
      locale: "en",
    },
    address: {
      street: "VENUE TNG Youth and Community Centre,, 111 Wells Park Rd",
      postalCode: "SE266AD",
      city: "London",
      countryCode: "GB",
      country: "United Kingdom",
    },
    category: ["other"],
    coordinates: [51.4307465, -0.0679717],
    similarEvents: [],
    tags: [
      "London",
      " Testing",
      " Software",
      " Coding",
      " Course",
      " Workshop",
    ],
    _id: "5e0f0e538452210017d775b1",
    name: "Software Testing",
    description:
      "Highlights of this course:\n\nSoftware Testing (Manual & Automation)\n\nNO previous qualification or experience required.\n\nComprehensive support from skilled professionals.\n\nOur quality training standards helps participants in achieving ISEB foundation certification.\n\nGood career prospects and excellent pay packages.",
    date: 1593334740000,
    imageUrl:
      "https://local-events-react.s3.amazonaws.com/2020-01-03T09%3A50%3A09.778Z-software-testing.jpg",
    owner: {
      address: {
        street: "Radlinskeho 34",
        postalCode: "81710",
        city: "Bratislava",
        countryCode: "SK",
        country: "SM",
      },
      userRole: "admin",
      _id: "5d700df7dd776d0a9d0c0e17",
      firstName: "Martin",
      lastName: "Zahradnik",
      userName: "Matty",
      birthDate: 637754760000,
      phone: "+42190749188",
      image:
        "https://local-events-react.s3.us-east-2.amazonaws.com/2020-02-01T10%3A07%3A17.269Z-IMG_20190601_193137.jpg",
      email: "zahradnik.admin@gmail.com",
      gender: "male",
    },
  },
  {
    price: {
      price: 0,
      currency: "EUR",
      locale: "en",
    },
    address: {
      street: " The Kabbalah Centre, 12 Stratford Place",
      postalCode: "SW43AU",
      city: "London",
      countryCode: "GB",
      country: "United Kingdom",
    },
    category: ["wellness", "outdoor"],
    coordinates: [51.5152929, -0.1516423],
    similarEvents: [],
    tags: ["Meditation", " Kabbalistic"],
    _id: "5e10a335f366000017177851",
    name: "Kabbalistic Meditation: BREATH",
    description:
      "Throughout history, people from many different cultures have used meditation to find inner peace and wellness, as well as to access higher levels of consciousness. Kabbalistic Meditation aims to allow one to interact directly with the supernal worlds, striving to bring us closer to the Light. \n\nJoin us for a special series of 7 classes - with each class we will discuss a different Chakra and we will ‘breath’ into each. \n\nWednesdays at 10am & Thursdays at 7:30pm with Yael GreenPrice: £50 per session\n\n* 20 ppl max - pre-registration only* 1.5 hours* monthly",
    date: 1592919060000,
    imageUrl:
      "https://local-events-react.s3.us-east-2.amazonaws.com/2020-01-04T14%3A37%3A40.343Z-meditation.jpg",
    owner: {
      address: {
        street: "Radlinskeho 34",
        postalCode: "81710",
        city: "Bratislava",
        countryCode: "SK",
        country: "SM",
      },
      password: "aaa",
      passwordConfirm: "aaa",
      userRole: "admin",
      _id: "5d700df7dd776d0a9d0c0e17",
      firstName: "Martin",
      lastName: "Zahradnik",
      userName: "Matty",
      birthDate: 637754760000,
      phone: "+42190749188",
      image:
        "https://local-events-react.s3.us-east-2.amazonaws.com/2020-02-01T10%3A07%3A17.269Z-IMG_20190601_193137.jpg",
      email: "zahradnik.admin@gmail.com",
      gender: "male",
    },
  },
  {
    price: {
      price: 0,
      currency: "EUR",
      locale: "en",
    },
    address: {
      street: " The Kabbalah Centre, 12 Stratford Place",
      postalCode: "SW43AU",
      city: "London",
      countryCode: "GB",
      country: "United Kingdom",
    },
    category: ["wellness", "outdoor"],
    coordinates: [51.5152929, -0.1516423],
    similarEvents: [],
    tags: ["Meditation", " Kabbalistic"],
    _id: "5e10a335f36600001123851",
    name: "Kabbalistic Meditation: BREATH",
    description:
      "Throughout history, people from many different cultures have used meditation to find inner peace and wellness, as well as to access higher levels of consciousness. Kabbalistic Meditation aims to allow one to interact directly with the supernal worlds, striving to bring us closer to the Light. \n\nJoin us for a special series of 7 classes - with each class we will discuss a different Chakra and we will ‘breath’ into each. \n\nWednesdays at 10am & Thursdays at 7:30pm with Yael GreenPrice: £50 per session\n\n* 20 ppl max - pre-registration only* 1.5 hours* monthly",
    date: 1592919060000,
    imageUrl:
      "https://local-events-react.s3.us-east-2.amazonaws.com/2020-01-04T14%3A37%3A40.343Z-meditation.jpg",
    owner: {
      address: {
        street: "Radlinskeho 34",
        postalCode: "81710",
        city: "Bratislava",
        countryCode: "SK",
        country: "SM",
      },
      password: "aaa",
      passwordConfirm: "aaa",
      userRole: "admin",
      _id: "5d700df7dd776d0a9d0c0e17",
      firstName: "Martin",
      lastName: "Zahradnik",
      userName: "Matty",
      birthDate: 637754760000,
      phone: "+42190749188",
      image:
        "https://local-events-react.s3.us-east-2.amazonaws.com/2020-02-01T10%3A07%3A17.269Z-IMG_20190601_193137.jpg",
      email: "zahradnik.admin@gmail.com",
      gender: "male",
    },
  },
  {
    price: {
      price: 0,
      currency: "EUR",
      locale: "en",
    },
    address: {
      street: " The Kabbalah Centre, 12 Stratford Place",
      postalCode: "SW43AU",
      city: "London",
      countryCode: "GB",
      country: "United Kingdom",
    },
    category: ["wellness", "outdoor"],
    coordinates: [51.5152929, -0.1516423],
    similarEvents: [],
    tags: ["Meditation", " Kabbalistic"],
    _id: "5e10a335f366000017177123",
    name: "Kabbalistic Meditation: BREATH",
    description:
      "Throughout history, people from many different cultures have used meditation to find inner peace and wellness, as well as to access higher levels of consciousness. Kabbalistic Meditation aims to allow one to interact directly with the supernal worlds, striving to bring us closer to the Light. \n\nJoin us for a special series of 7 classes - with each class we will discuss a different Chakra and we will ‘breath’ into each. \n\nWednesdays at 10am & Thursdays at 7:30pm with Yael GreenPrice: £50 per session\n\n* 20 ppl max - pre-registration only* 1.5 hours* monthly",
    date: 1592919060000,
    imageUrl:
      "https://local-events-react.s3.us-east-2.amazonaws.com/2020-01-04T14%3A37%3A40.343Z-meditation.jpg",
    owner: {
      address: {
        street: "Radlinskeho 34",
        postalCode: "81710",
        city: "Bratislava",
        countryCode: "SK",
        country: "SM",
      },
      password: "aaa",
      passwordConfirm: "aaa",
      userRole: "admin",
      _id: "5d700df7dd776d0a9d0c0e17",
      firstName: "Martin",
      lastName: "Zahradnik",
      userName: "Matty",
      birthDate: 637754760000,
      phone: "+42190749188",
      image:
        "https://local-events-react.s3.us-east-2.amazonaws.com/2020-02-01T10%3A07%3A17.269Z-IMG_20190601_193137.jpg",
      email: "zahradnik.admin@gmail.com",
      gender: "male",
    },
  },
];

export const getMockedEvents = (slice = 10) => mockedEvents.slice(0, slice);
