export const FETCH_COUNTRY_LIST = "events/FETCH_COUNTRY_LIST";
export const FETCH_COUNTRY_LIST_SUCCESS = "events/FETCH_COUNTRY_LIST_SUCCESS";
export const FETCH_COUNTRY_LIST_ERROR = "events/FETCH_COUNTRY_LIST_ERROR";
