export const actionTypes = {
  FETCH_COUNTRY_LIST: "events/FETCH_COUNTRY_LIST",
  FETCH_COUNTRY_LIST_SUCCESS: "events/FETCH_COUNTRY_LIST_SUCCESS",
  FETCH_COUNTRY_LIST_ERROR: "events/FETCH_COUNTRY_LIST_ERROR"
};
