export const actionTypes = {
  FETCH_USER: "user/FETCH_USER",
  FETCH_USER_SUCCESS: "user/FETCH_USER_SUCCESS",
  FETCH_USER_ERROR: "user/FETCH_USER_SUCCESS",

  // LOGIN
  LOGIN: "user/LOGIN",
  LOGIN_SUCCESS: "user/LOGIN_SUCCESS",
  LOGIN_ERROR: "user/LOGIN_ERROR",
  LOGOUT: "user/LOGOUT",

  // PASSWORD RESET
  PASSWORD_RESET: "user/PASSWORD_RESET",
  PASSWORD_RESET_SUCCESS: "user/PASSWORD_RESET_SUCCESS",
  PASSWORD_RESET_ERROR: "user/PASSWORD_RESET_ERROR",

  // REGISTER_USER
  REGISTER_USER: "user/REGISTER_USER",
  REGISTER_USER_SUCCESS: "user/REGISTER_USER_SUCCESS",
  REGISTER_USER_ERROR: "user/REGISTER_USER_ERROR",

  // UPDATE_USER
  UPDATE_USER: "user/UPDATE_USER",
  UPDATE_USER_SUCCESS: "user/UPDATE_USER_SUCCESS",
  UPDATE_USER_ERROR: "user/UPDATE_USER_ERROR",

  // SET_NEW_PASSWORD
  SET_NEW_PASSWORD: "user/SET_NEW_PASSWORD"
};
