export const actionTypes = {
  FETCH_USER: "user/FETCH_USER",
  FETCH_USER_SUCCESS: "user/FETCH_USER_SUCCESS",
  FETCH_USER_ERROR: "user/FETCH_USER_SUCCESS",

  // LOGIN
  LOGIN: "user/LOGIN",
  LOGIN_SUCCESS: "user/LOGIN_SUCCESS",
  LOGIN_ERROR: "user/LOGIN_ERROR",
  LOGOUT: "user/LOGOUT",

  PASSWORD_RESET: "user/PASSWORD_RESET",
  PASSWORD_RESET_SUCCESS: "user/PASSWORD_RESET_SUCCESS",
  PASSWORD_RESET_ERROR: "user/PASSWORD_RESET_ERROR"
};
