export const FETCH_EVENTS = "events/FETCH_EVENTS";
export const FETCH_EVENTS_SUCCESS = "events/FETCH_EVENTS_SUCCESS";
export const FETCH_EVENTS_ERROR = "events/FETCH_EVENTS_ERROR";

// FETCH EVENT DETAIL
export const FETCH_EVENT_DETAIL = "events/FETCH_EVENT_DETAIL";
export const FETCH_EVENT_DETAIL_SUCCESS = "events/FETCH_EVENT_DETAIL_SUCCESS";
export const FETCH_EVENT_DETAIL_ERROR = "events/FETCH_EVENT_DETAIL_ERROR";

// CREATE EVENT
export const CREATE_EVENT = "events/CREATE_EVENT";
export const CREATE_EVENT_SUCCESS = "events/CREATE_EVENT_SUCCESS";
export const CREATE_EVENT_ERROR = "events/CREATE_EVENT_ERROR";

// UPDATE EVENT
export const UPDATE_EVENT = "events/UPDATE_EVENT";
export const UPDATE_EVENT_SUCCESS = "events/UPDATE_EVENT_SUCCESS";
export const UPDATE_EVENT_ERROR = "events/UPDATE_EVENT_ERROR";

// EVENTS BY USER ID
export const FETCH_EVENTS_BY_USER_ID = "events/FETCH_EVENTS_BY_USER_ID";
export const FETCH_EVENTS_BY_USER_ID_SUCCESS =
  "events/FETCH_EVENTS_BY_USER_ID_SUCCESS";
export const FETCH_EVENTS_BY_USER_ID_ERROR =
  "events/FETCH_EVENTS_BY_USER_ID_ERROR";

// DELETE EVENTS
export const DELETE_EVENT = "events/DELETE_EVENT";
export const DELETE_EVENT_SUCCESS = "events/DELETE_EVENT_SUCCESS";
export const DELETE_EVENT_ERROR = "events/DELETE_EVENT_ERROR";

// Others
export const SET_SEARCH_TERM = "events/SET_SEARCH_TERM";
export const SET_SEARCH_CITY = "events/SET_SEARCH_CITY";
