export const actionTypes = {
  FETCH_EVENTS: "events/FETCH_EVENTS",
  FETCH_EVENTS_SUCCESS: "events/FETCH_EVENTS_SUCCESS",
  FETCH_EVENTS_ERROR: "events/FETCH_EVENTS_ERROR",

  // FETCH EVENT DETAIL
  FETCH_EVENT_DETAIL: "events/FETCH_EVENT_DETAIL",
  FETCH_EVENT_DETAIL_SUCCESS: "events/FETCH_EVENT_DETAIL_SUCCESS",
  FETCH_EVENT_DETAIL_ERROR: "events/FETCH_EVENT_DETAIL_ERROR",

  // CREATE EVENT
  CREATE_EVENT: "events/CREATE_EVENT",
  CREATE_EVENT_SUCCESS: "events/CREATE_EVENT_SUCCESS",
  CREATE_EVENT_ERROR: "events/CREATE_EVENT_ERROR",

  // UPDATE EVENT
  UPDATE_EVENT: "events/UPDATE_EVENT",
  UPDATE_EVENT_SUCCESS: "events/UPDATE_EVENT_SUCCESS",
  UPDATE_EVENT_ERROR: "events/UPDATE_EVENT_ERROR",

  // EVENTS BY USER ID
  FETCH_EVENTS_BY_USER_ID: "events/FETCH_EVENTS_BY_USER_ID",
  FETCH_EVENTS_BY_USER_ID_SUCCESS: "events/FETCH_EVENTS_BY_USER_ID_SUCCESS",
  FETCH_EVENTS_BY_USER_ID_ERROR: "events/FETCH_EVENTS_BY_USER_ID_ERROR",

  // DELETE EVENTS
  DELETE_EVENT: "events/DELETE_EVENT",
  DELETE_EVENT_SUCCESS: "events/DELETE_EVENT_SUCCESS",
  DELETE_EVENT_ERROR: "events/DELETE_EVENT_ERROR",

  // Others
  SET_SEARCH_TERM: "events/SET_SEARCH_TERM",
  SET_SEARCH_CITY: "events/SET_SEARCH_CITY"
};
