export const FETCH_EVENT_DETAIL = "events/FETCH_EVENT_DETAIL";
export const FETCH_EVENT_DETAIL_SUCCESS = "events/FETCH_EVENT_DETAIL_SUCCESS";
export const FETCH_EVENT_DETAIL_ERROR = "events/FETCH_EVENT_DETAIL_ERROR";

export const RESET_EVENT_DETAIL = "events/RESET_EVENT_DETAIL";

export const FETCH_SIMILAR_EVENTS = "events/FETCH_SIMILAR_EVENTS";
export const FETCH_SIMILAR_EVENTS_SUCCESS =
  "events/FETCH_SIMILAR_EVENTS_SUCCESS";
export const FETCH_SIMILAR_EVENTS_ERROR = "events/FETCH_SIMILAR_EVENTS_ERROR";
