export const actionTypes = {
  FETCH_EVENT_DETAIL: "events/FETCH_EVENT_DETAIL",
  FETCH_EVENT_DETAIL_SUCCESS: "events/FETCH_EVENT_DETAIL_SUCCESS",
  FETCH_EVENT_DETAIL_ERROR: "events/FETCH_EVENT_DETAIL_ERROR",

  RESET_EVENT_DETAIL: "events/RESET_EVENT_DETAIL"
};
